# Imagen base que contiene Python y Flask
FROM python:3.9-slim

# Directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar los archivos de la aplicación a la imagen
COPY requirements.txt app.py /app/
COPY templates /app/templates/

# Instalar las dependencias de la aplicación
RUN pip install --no-cache-dir -r requirements.txt

# Exponer el puerto en el que se ejecutará la aplicación Flask (puede ser el mismo que se usa en la aplicación Flask)
EXPOSE 5000

# Comando para ejecutar la aplicación Flask
CMD ["python", "app.py"]